// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 27 Dec 2023 15:18:21 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cuda_runtime

/*
#cgo LDFLAGS: -L/usr/local/cuda/lib64 -lcudart
#cgo CFLAGS: -I /usr/local/cuda/include
#include <cuda.h>
#include <cuda_runtime.h>
#include <cuda_runtime_api.h>
#include <driver_types.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// cudaStreamDefault as defined in include/driver_types.h:98
	cudaStreamDefault = 0x00
	// cudaStreamNonBlocking as defined in include/driver_types.h:99
	cudaStreamNonBlocking = 0x01
	// cudaEventWaitDefault as defined in include/driver_types.h:129
	cudaEventWaitDefault = 0x00
	// cudaEventWaitExternal as defined in include/driver_types.h:130
	cudaEventWaitExternal = 0x01
)

// cudaErrorT as declared in include/driver_types.h:2792
type cudaErrorT int32

// cudaErrorT enumeration from include/driver_types.h:2792
const (
	cudaErrorInvalidValue                   cudaErrorT = 1
	cudaErrorMemoryAllocation               cudaErrorT = 2
	cudaErrorInitializationError            cudaErrorT = 3
	cudaErrorCudartUnloading                cudaErrorT = 4
	cudaErrorProfilerDisabled               cudaErrorT = 5
	cudaErrorProfilerNotInitialized         cudaErrorT = 6
	cudaErrorProfilerAlreadyStarted         cudaErrorT = 7
	cudaErrorProfilerAlreadyStopped         cudaErrorT = 8
	cudaErrorInvalidConfiguration           cudaErrorT = 9
	cudaErrorInvalidPitchValue              cudaErrorT = 12
	cudaErrorInvalidSymbol                  cudaErrorT = 13
	cudaErrorInvalidHostPointer             cudaErrorT = 16
	cudaErrorInvalidDevicePointer           cudaErrorT = 17
	cudaErrorInvalidTexture                 cudaErrorT = 18
	cudaErrorInvalidTextureBinding          cudaErrorT = 19
	cudaErrorInvalidChannelDescriptor       cudaErrorT = 20
	cudaErrorInvalidMemcpyDirection         cudaErrorT = 21
	cudaErrorAddressOfConstant              cudaErrorT = 22
	cudaErrorTextureFetchFailed             cudaErrorT = 23
	cudaErrorTextureNotBound                cudaErrorT = 24
	cudaErrorSynchronizationError           cudaErrorT = 25
	cudaErrorInvalidFilterSetting           cudaErrorT = 26
	cudaErrorInvalidNormSetting             cudaErrorT = 27
	cudaErrorMixedDeviceExecution           cudaErrorT = 28
	cudaErrorNotYetImplemented              cudaErrorT = 31
	cudaErrorMemoryValueTooLarge            cudaErrorT = 32
	cudaErrorStubLibrary                    cudaErrorT = 34
	cudaErrorInsufficientDriver             cudaErrorT = 35
	cudaErrorCallRequiresNewerDriver        cudaErrorT = 36
	cudaErrorInvalidSurface                 cudaErrorT = 37
	cudaErrorDuplicateVariableName          cudaErrorT = 43
	cudaErrorDuplicateTextureName           cudaErrorT = 44
	cudaErrorDuplicateSurfaceName           cudaErrorT = 45
	cudaErrorDevicesUnavailable             cudaErrorT = 46
	cudaErrorIncompatibleDriverContext      cudaErrorT = 49
	cudaErrorMissingConfiguration           cudaErrorT = 52
	cudaErrorPriorLaunchFailure             cudaErrorT = 53
	cudaErrorLaunchMaxDepthExceeded         cudaErrorT = 65
	cudaErrorLaunchFileScopedTex            cudaErrorT = 66
	cudaErrorLaunchFileScopedSurf           cudaErrorT = 67
	cudaErrorSyncDepthExceeded              cudaErrorT = 68
	cudaErrorLaunchPendingCountExceeded     cudaErrorT = 69
	cudaErrorInvalidDeviceFunction          cudaErrorT = 98
	cudaErrorNoDevice                       cudaErrorT = 100
	cudaErrorInvalidDevice                  cudaErrorT = 101
	cudaErrorDeviceNotLicensed              cudaErrorT = 102
	cudaErrorSoftwareValidityNotEstablished cudaErrorT = 103
	cudaErrorStartupFailure                 cudaErrorT = 127
	cudaErrorInvalidKernelImage             cudaErrorT = 200
	cudaErrorDeviceUninitialized            cudaErrorT = 201
	cudaErrorMapBufferObjectFailed          cudaErrorT = 205
	cudaErrorUnmapBufferObjectFailed        cudaErrorT = 206
	cudaErrorArrayIsMapped                  cudaErrorT = 207
	cudaErrorAlreadyMapped                  cudaErrorT = 208
	cudaErrorNoKernelImageForDevice         cudaErrorT = 209
	cudaErrorAlreadyAcquired                cudaErrorT = 210
	cudaErrorNotMapped                      cudaErrorT = 211
	cudaErrorNotMappedAsArray               cudaErrorT = 212
	cudaErrorNotMappedAsPointer             cudaErrorT = 213
	cudaErrorECCUncorrectable               cudaErrorT = 214
	cudaErrorUnsupportedLimit               cudaErrorT = 215
	cudaErrorDeviceAlreadyInUse             cudaErrorT = 216
	cudaErrorPeerAccessUnsupported          cudaErrorT = 217
	cudaErrorInvalidPtx                     cudaErrorT = 218
	cudaErrorInvalidGraphicsContext         cudaErrorT = 219
	cudaErrorNvlinkUncorrectable            cudaErrorT = 220
	cudaErrorJitCompilerNotFound            cudaErrorT = 221
	cudaErrorUnsupportedPtxVersion          cudaErrorT = 222
	cudaErrorJitCompilationDisabled         cudaErrorT = 223
	cudaErrorUnsupportedExecAffinity        cudaErrorT = 224
	cudaErrorUnsupportedDevSideSync         cudaErrorT = 225
	cudaErrorInvalidSource                  cudaErrorT = 300
	cudaErrorFileNotFound                   cudaErrorT = 301
	cudaErrorSharedObjectSymbolNotFound     cudaErrorT = 302
	cudaErrorSharedObjectInitFailed         cudaErrorT = 303
	cudaErrorOperatingSystem                cudaErrorT = 304
	cudaErrorInvalidResourceHandle          cudaErrorT = 400
	cudaErrorIllegalState                   cudaErrorT = 401
	cudaErrorSymbolNotFound                 cudaErrorT = 500
	cudaErrorNotReady                       cudaErrorT = 600
	cudaErrorIllegalAddress                 cudaErrorT = 700
	cudaErrorLaunchOutOfResources           cudaErrorT = 701
	cudaErrorLaunchTimeout                  cudaErrorT = 702
	cudaErrorLaunchIncompatibleTexturing    cudaErrorT = 703
	cudaErrorPeerAccessAlreadyEnabled       cudaErrorT = 704
	cudaErrorPeerAccessNotEnabled           cudaErrorT = 705
	cudaErrorSetOnActiveProcess             cudaErrorT = 708
	cudaErrorContextIsDestroyed             cudaErrorT = 709
	cudaErrorAssert                         cudaErrorT = 710
	cudaErrorTooManyPeers                   cudaErrorT = 711
	cudaErrorHostMemoryAlreadyRegistered    cudaErrorT = 712
	cudaErrorHostMemoryNotRegistered        cudaErrorT = 713
	cudaErrorHardwareStackError             cudaErrorT = 714
	cudaErrorIllegalInstruction             cudaErrorT = 715
	cudaErrorMisalignedAddress              cudaErrorT = 716
	cudaErrorInvalidAddressSpace            cudaErrorT = 717
	cudaErrorInvalidPc                      cudaErrorT = 718
	cudaErrorLaunchFailure                  cudaErrorT = 719
	cudaErrorCooperativeLaunchTooLarge      cudaErrorT = 720
	cudaErrorNotPermitted                   cudaErrorT = 800
	cudaErrorNotSupported                   cudaErrorT = 801
	cudaErrorSystemNotReady                 cudaErrorT = 802
	cudaErrorSystemDriverMismatch           cudaErrorT = 803
	cudaErrorCompatNotSupportedOnDevice     cudaErrorT = 804
	cudaErrorMpsConnectionFailed            cudaErrorT = 805
	cudaErrorMpsRpcFailure                  cudaErrorT = 806
	cudaErrorMpsServerNotReady              cudaErrorT = 807
	cudaErrorMpsMaxClientsReached           cudaErrorT = 808
	cudaErrorMpsMaxConnectionsReached       cudaErrorT = 809
	cudaErrorMpsClientTerminated            cudaErrorT = 810
	cudaErrorCdpNotSupported                cudaErrorT = 811
	cudaErrorCdpVersionMismatch             cudaErrorT = 812
	cudaErrorStreamCaptureUnsupported       cudaErrorT = 900
	cudaErrorStreamCaptureInvalidated       cudaErrorT = 901
	cudaErrorStreamCaptureMerge             cudaErrorT = 902
	cudaErrorStreamCaptureUnmatched         cudaErrorT = 903
	cudaErrorStreamCaptureUnjoined          cudaErrorT = 904
	cudaErrorStreamCaptureIsolation         cudaErrorT = 905
	cudaErrorStreamCaptureImplicit          cudaErrorT = 906
	cudaErrorCapturedEvent                  cudaErrorT = 907
	cudaErrorStreamCaptureWrongThread       cudaErrorT = 908
	cudaErrorTimeout                        cudaErrorT = 909
	cudaErrorGraphExecUpdateFailure         cudaErrorT = 910
	cudaErrorExternalDevice                 cudaErrorT = 911
	cudaErrorInvalidClusterSize             cudaErrorT = 912
	cudaErrorUnknown                        cudaErrorT = 999
	cudaErrorApiFailureBase                 cudaErrorT = 10000
)

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()
