// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 27 Dec 2023 15:18:21 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package runtime provides Go bindings
*/
package cuda_runtime
