// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 27 Dec 2023 15:18:21 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cuda_runtime

/*
#cgo LDFLAGS: -L/usr/local/cuda/lib64 -lcudart
#cgo CFLAGS: -I /usr/local/cuda/include
#include <cuda.h>
#include <cuda_runtime.h>
#include <cuda_runtime_api.h>
#include <driver_types.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// cudaStreamT as declared in include/driver_types.h:2797
type cudaStreamT C.struct_CUstream_st

// cudaEventT as declared in include/driver_types.h:2802
type cudaEventT C.struct_CUevent_st
