// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 24 Jan 2024 15:49:59 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <cuda.h>
#include <cuda_runtime.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

