// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 24 Jan 2024 14:54:24 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void cudaStreamCallback_t_9f346d76(struct CUstream_st stream, cudaError_t status, void* userData) {
	cudaStreamCallbackT9F346D76(stream, status, userData);
}

void cudaHostFn_t_a8677e8a(void* userData) {
	cudaHostFnTA8677E8A(userData);
}

