// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 24 Jan 2024 15:49:59 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cuda_bindings

/*
#cgo LDFLAGS: -L/usr/local/cuda/lib64 -lcudart
#cgo CFLAGS: -I /usr/local/cuda/include
#include <cuda.h>
#include <cuda_runtime.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// CudaStream as declared in include/driver_types.h:2873
type CudaStream C.struct_CUstream_st

// CudaEvent as declared in include/driver_types.h:2878
type CudaEvent C.struct_CUevent_st
